import type { PartnerHospital } from '@/features/hospitals/types/partnerHospital.types';

/** Demo partner network — replace with GET /hospitals from backend. */
export const MOCK_PARTNER_HOSPITALS: PartnerHospital[] = [
  {
    id: 'h1',
    name: 'Island Family Clinic',
    address: '12 Admiralty Way, Lekki Phase 1',
    state: 'Lagos',
    lga: 'Eti-Osa',
    phone: '+2348012345601',
    latitude: 6.4474,
    longitude: 3.4723,
    services: ['Malaria', 'Typhoid', 'Consultation'],
  },
  {
    id: 'h2',
    name: 'Ikeja Community Health Centre',
    address: '44 Allen Avenue, Ikeja',
    state: 'Lagos',
    lga: 'Ikeja',
    phone: '+2348012345602',
    latitude: 6.6018,
    longitude: 3.3515,
    services: ['Consultation', 'Minor injuries', 'Basic drugs'],
  },
  {
    id: 'h3',
    name: 'Surulere Primary Care Hub',
    address: '8 Bode Thomas Street, Surulere',
    state: 'Lagos',
    lga: 'Surulere',
    phone: '+2348012345603',
    latitude: 6.4969,
    longitude: 3.3584,
    services: ['Malaria', 'Wound care', 'Consultation'],
  },
  {
    id: 'h4',
    name: 'Yaba QuickCare Clinic',
    address: '3 Herbert Macaulay Way, Yaba',
    state: 'Lagos',
    lga: 'Lagos Mainland',
    phone: '+2348012345604',
    latitude: 6.5155,
    longitude: 3.3711,
    services: ['Typhoid', 'Consultation', 'Basic drugs'],
  },
  {
    id: 'h5',
    name: 'Ajah Neighbourhood Hospital',
    address: '21 Lekki-Epe Expressway, Ajah',
    state: 'Lagos',
    lga: 'Eti-Osa',
    phone: '+2348012345605',
    latitude: 6.4683,
    longitude: 3.5822,
    services: ['Malaria', 'Consultation', 'Minor injuries'],
  },
  {
    id: 'h6',
    name: 'Maryland Wellness Clinic',
    address: '15 Ikorodu Road, Maryland',
    state: 'Lagos',
    lga: 'Kosofe',
    phone: '+2348012345606',
    latitude: 6.5789,
    longitude: 3.3672,
    services: ['Consultation', 'Basic drugs'],
  },
  {
    id: 'h7',
    name: 'Abuja Central Polyclinic',
    address: '9 Gimbiya Street, Area 11',
    state: 'FCT',
    lga: 'Abuja Municipal',
    phone: '+2348012345607',
    latitude: 9.0579,
    longitude: 7.4951,
    services: ['Malaria', 'Typhoid', 'Consultation'],
  },
  {
    id: 'h8',
    name: 'Port Harcourt Riverside Clinic',
    address: '2 Creek Road, Port Harcourt',
    state: 'Rivers',
    lga: 'Port Harcourt',
    phone: '+2348012345608',
    latitude: 4.7774,
    longitude: 7.0134,
    services: ['Consultation', 'Wound care', 'Basic drugs'],
  },
];

export function getPartnerHospitalById(id: string): PartnerHospital | undefined {
  return MOCK_PARTNER_HOSPITALS.find((h) => h.id === id);
}
